import axios from 'axios';

const Instance = axios.create({
  headers: {
    Authorization:
      'Bearer ' +
      'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb3JraW1Ac3R1ZGVudC40MnNlb3VsLmtyIiwiaXNzIjoiaHR0cDovLzEyNy4wLjAuMTo4MDgwL2xvZ2luL29hdXRoMi9jb2RlL2F1dGhjbGllbnQiLCJleHAiOjE2NzA1Nzc1NjQsImF1dGhvcml0aWVzIjpbInVzZXIuZGVsZXRlIiwiYXJ0aWNsZS5yZWFkIiwibWF0Y2guY3JlYXRlIiwidXNlci51cGRhdGUiLCJtYXRjaC5yZWFkIiwicmFuZG9tLW1hdGNoLnVwZGF0ZSIsIm9waW5pb24uY3JlYXRlIiwib3Bpbmlvbi5kZWxldGUiLCJhcnRpY2xlLnVwZGF0ZSIsImFjdGl2aXR5LmRlbGV0ZSIsImFydGljbGUuZGVsZXRlIiwicmFuZG9tLW1hdGNoLmNyZWF0ZSIsIm1hdGNoLnVwZGF0ZSIsInVzZXIucmVhZCIsInVzZXIuY3JlYXRlIiwiYWN0aXZpdHkudXBkYXRlIiwiYWN0aXZpdHkuY3JlYXRlIiwiYXJ0aWNsZS5jcmVhdGUiLCJtYXRjaC5kZWxldGUiLCJyYW5kb20tbWF0Y2gucmVhZCIsImFjdGl2aXR5LnJlYWQiLCJyYW5kb20tbWF0Y2guZGVsZXRlIiwib3Bpbmlvbi51cGRhdGUiLCJvcGluaW9uLnJlYWQiXX0.oM0shc77A_GZPr7na4mgl9QYDl_0GyHkOGQX0pPTq8Q',
  },
});

export default Instance;
